server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  security:
    user:
      name: user
      password: 1234
  application:
    name: support
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/support_test?serverTimezone=Asia/Seoul
    username: supportTester
    password: Qwer1234*
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        highlight_sql: true
    open-in-view: true
  mail:
    host: smtp.naver.com
    port: 465
    username: supportofficial@naver.com
    password: XSSUF8781GJL
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          ssl:
            enable: true
            protocols: TLSv1.2
  data:
    redis:
      host: localhost
      port: 6379

admin:
  loginId: admin
  password: adminpassword

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        type.descriptor.sql: trace
        SQL: debug
      springframework:
        mail: debug
jwt:
  access_secret: DadFufN4Oui8Bfv3ScFj6R9fyJ9hD45EdasdasaD6AGaF15waFAS1326SDFsXgFs
  refresh_secret: 45EdasdasaD6AGaF15DadFufN4Oui8Bfv3ScFj6RwaFASD515sdasdASD5ASD515