server:
  port: 9999
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  security:
    user:
      name: user
      password: 1234
  application:
    name: support
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/support_test?serverTimezone=Asia/Seoul
    username: supportTester
    password: qwer1234*
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        highlight_sql: true
    open-in-view: true
  mail:
    host: smtp.naver.com
    port: 465
    username: supportofficial@naver.com
    password: XSSUF8781GJL
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          ssl:
            enable: true
            protocols: TLSv1.2
  redis:
    post: 6379
  data:
    redis:
      host: localhost

logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        type.descriptor.sql: trace
        SQL: debug
      springframework:
        mail: debug
jwt:
  secret: DadFufN4Oui8Bfv3ScFj6R9fyJ9hD45EdasdasaD6AGaF15waFAS1326SDFsXgFsRhT4YSdSb5SD515ASDASD515sdasdASD5ASD515ASDASDaDSAFAF1169W1sdaw