POST localhost:9999/member/mail
Content-Type: application/json

{
    "loginId":"barbo9510"
}

###
POST localhost:9999/member/mailcheck
Content-Type: application/json

{
  "loginId": "barbo9510",
  "authCode": "8b1ca6"
}