### 스케줄 작성
POST localhost:8080/schedule/add
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "title":"제목입니다",
  "content":"내용입니다",
  "startDate":"2024-08-20",
  "endDate":"2024-08-16",
  "color":4
}
### 지정 스케줄 꺼내오기
GET localhost:8080/schedule/1

### 월별 스케줄 꺼내오기
GET localhost:8080/schedule?date=2024-08

### 공지사항 작성
POST localhost:8080/notification/add
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "title":"제목",
  "content":"내용"
}
### 공지사항불러오기
GET localhost:8080/notification
### 지정 공지사항 꺼내오기
GET localhost:8080/notification/2
### 공지사항 수정
PUT localhost:8080/notification/edit
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "id": 2,
  "title": "aㅁㅁㅁㅁㅁㅁㅁ",
  "content": "ㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁㅁ"
}
### 공지사항 삭제
DELETE localhost:8080/notification/2/delete
Authorization: Bearer {{adminToken}}
###