###이메일 인증
POST localhost:8080/member/mail
Content-Type: application/json

{
  "loginId":"barbo9510"
}

###이메일 인증 확인 {mail}@icloud.com
POST localhost:8080/member/mailcheck
Content-Type: application/json

{
  "loginId": "barbo9510",
  "authCode": "7ecc41"
}
###회원가입
POST localhost:8080/member/signup
Content-Type: application/json

{
  "loginId":"2101817",
  "password": "qwer1234*",
  "nickname":"수원대행정실",
  "gender":"MAN",
  "dormType":"GyungM",
  "dormNo":876,
  "roomNo":""
}

###로그인
POST localhost:8080/member/login
Content-Type: application/json

{
  "loginId":"2101817",
  "password":"qwer1234*"
}
> {%
 client.global.set("acToken",response.body.data.accessToken);
 client.global.set("reToken",response.body.data.refreshToken);
%}
###어드민 로그인
POST localhost:8080/member/login
Content-Type: application/json

{
  "loginId":"2101817",
  "password":"qwer1234*"
}
> {%
    client.global.set("adminToken",response.body.data.accessToken);
%}

###로그인
POST localhost:8080/member/login
Content-Type: application/json

{
  "loginId":"admin",
  "password":"adminpassword"
}

### 내정보
GET localhost:8080/member/info
Authorization: Bearer {{acToken}}

### 비밀번호 찾기
POST localhost:8080/member/mail/find?loginId=2101817

### 내 정보 수정
PUT localhost:8080/member/info
Content-Type: application/json
Authorization: Bearer {{acToken}}

{
  "nickname":"수원대행정실",
  "gender":"WOMAN",
  "dormType":"GyungM",
  "dormNo":876,
  "roomNo": null
}
###